[package]
name = "graphnn-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = "0.19.1"
enum_dispatch = "0.3.13"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
